### PR TITLE
Campaigner improvement.

### LINKED ISSUE #1096: Implement campaign logs
When sending a campaign, the user will have no visibility when the campaigner consumer fails to send the campaign successfully. We'll need to implement an immutable log of events for each campaign that is being sent.

### PR DESCRIPTION
**Pull request by Dzalevski**
# Pull Request Template

## Description

Added new table campaign failed logs, improvement  in campaigns consumer touch() for resetting timeout timer, on status update insert failed log.

Fixes 
#1096 
#1097 
#1098 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Test A unit tests
- [x] Tested with sending actual campaign.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: consumers/campaigner/main.go [hunk 1]
```diff
@@ -243,12 +246,40 @@ func processSubscribers(
...
+		return
+	}
+	log := &entities.CampaignFailedLog{
+		ID:          ksuid.New(),
+		UserID:      msg.UserID,
+		CampaignID:  msg.CampaignID,
+		Description: "Exceeded max attempts for preparing the campaign",
+		CreatedAt:   time.Time{},
+	}
+	err = storage.CreateCampaignFailedLog(context.Background(), log)
```
Comment (gudgl) [inline consumers/campaigner/main.go:268]: there is no database in context.Background() you can use the store from MessageHandler (h.store)

File: consumers/campaigner/main.go [hunk 2]
```diff
@@ -243,12 +246,40 @@ func processSubscribers(
...
+	if m == nil {
+		return
+	}
+	msg := new(entities.CampaignerTopicParams)
+	err := json.Unmarshal(m.Body, &msg)
+	if err != nil {
+		logrus.WithField("body", string(m.Body)).
+			WithError(err).Error("Malformed JSON message.")
+		return
+	}
```
Comment (gudgl) [inline consumers/campaigner/main.go:260]: Add error log here

File: storage/campaignfailedlog.go [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+	tx := db.Begin()
+	defer func() {
+		if r := recover(); r != nil {
+			tx.Rollback()
+		}
+	}()
+
+	err := tx.Model(&entities.Campaign{}).
+		Where("id = ? AND user_id = ?", c.ID, c.UserID).
+		Update("status", "failed").Error
```
Comment (gudgl) [inline storage/campaignfailedlog.go:26]: there is constant for failed status

File: consumers/campaigner/main.go (hunk 1 above)
Comment (gudgl) [reply consumers/campaigner/main.go:268]: Also i think we should update the campaign status here as well

Comment (Dzalevski) [reply consumers/campaigner/main.go:268]: CampaignFailedLog is doing that in transaction @gudgl

File: consumers/campaigner/main.go [hunk 4]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+	logrus.WithFields(logrus.Fields{
+		"user_id":     msg.UserID,
+		"campaign_id": msg.CampaignID,
+	}).Error("Exceeded max attempts for sending the e-mail.")
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:264]:
```suggestion
	}).Error("exceeded max attempts for sending the campaign")
```

File: consumers/campaigner/main.go [hunk 5]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+
+	log := &entities.CampaignFailedLog{
+		ID:          ksuid.New(),
+		UserID:      msg.UserID,
+		CampaignID:  msg.CampaignID,
+		Description: "Exceeded max attempts for preparing the campaign",
+		CreatedAt:   time.Time{},
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:271]: No need to add the CreatedAt here.

File: consumers/campaigner/main.go [hunk 6]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+	}
+	campaign, err := storage.GetCampaign(context.Background(), msg.CampaignID, msg.UserID)
+	if err != nil {
+		logrus.WithField("campaign_id", msg.CampaignID).
+			WithError(err).Error("Failed to get campaign.")
+		return
+	}
+	err = storage.LogFailedCampaign(context.Background(), campaign, log)
+	if err != nil {
+		logrus.WithField("log", log).
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:281]: Don't add the whole log object here.

File: consumers/campaigner/main.go [hunk 7]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+	log := &entities.CampaignFailedLog{
+		ID:          ksuid.New(),
+		UserID:      msg.UserID,
+		CampaignID:  msg.CampaignID,
+		Description: "Exceeded max attempts for preparing the campaign",
+		CreatedAt:   time.Time{},
+	}
+	campaign, err := storage.GetCampaign(context.Background(), msg.CampaignID, msg.UserID)
+	if err != nil {
+		logrus.WithField("campaign_id", msg.CampaignID).
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:275]: Add more fields such as the `user_id` etc.

File: consumers/campaigner/main.go [hunk 8]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+			WithError(err).Error("Failed to get campaign.")
+		return
+	}
+	err = storage.LogFailedCampaign(context.Background(), campaign, log)
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:279]: use the storage from the handler, context does not contain the storage entity.

File: consumers/campaigner/main.go [hunk 9]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
+	}).Error("Exceeded max attempts for sending the e-mail.")
+
+	log := &entities.CampaignFailedLog{
+		ID:          ksuid.New(),
+		UserID:      msg.UserID,
+		CampaignID:  msg.CampaignID,
+		Description: "Exceeded max attempts for preparing the campaign",
+		CreatedAt:   time.Time{},
+	}
+	campaign, err := storage.GetCampaign(context.Background(), msg.CampaignID, msg.UserID)
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:273]: Don't use the storage from context here as well.

File: consumers/campaigner/main.go [hunk 10]
```diff
@@ -243,12 +246,58 @@ func processSubscribers(
...
 	defer trace.StartRegion(ctx, "setStatusFailed").End()
 
 	campaign.Status = entities.StatusFailed
 	campaign.CompletedAt.SetValid(time.Now().UTC())
-	return store.UpdateCampaign(campaign)
+	log := &entities.CampaignFailedLog{
+		ID:          ksuid.New(),
+		UserID:      campaign.UserID,
+		CampaignID:  campaign.ID,
+		Description: "Failed to prepare campaign",
```
Comment (FilipNikolovski) [inline consumers/campaigner/main.go:297]: The description depends on where we invoke the `logFailedCampaign` func. I think we should add it as an argument in the function.

File: storage/campaignfailedlog.go [hunk 11]
```diff
@@ -0,0 +1,37 @@
...
+
+	"github.com/mailbadger/app/entities"
+)
+
+// CreateReport creates a report.
+func (db *store) CreateCampaignFailedLog(l *entities.CampaignFailedLog) error {
+	return db.Create(l).Error
+}
+
+func (db *store) LogFailedCampaign(c *entities.Campaign, log *entities.CampaignFailedLog) error {
```
Comment (FilipNikolovski) [inline storage/campaignfailedlog.go:14]: Can we maybe create the log entity inside the method? It would be cleaner that way.

**Review by FilipNikolovski — CHANGES_REQUESTED** [review]

File: storage/migrations/mysql/5_campaign_logs.sql [hunk 12]
```diff
@@ -0,0 +1,15 @@
+-- +migrate Up
```
Comment (gudgl) [inline storage/migrations/mysql/5_campaign_logs.sql:1]: Double check the file name i think it should be 4 not 5

File: consumers/campaigner/main.go [hunk 13]
```diff
@@ -243,12 +246,44 @@ func processSubscribers(
...
+	err = h.s.LogFailedCampaign(campaign, "Exceeded max attempts for preparing the campaign")
+	if err != nil {
+		logrus.WithField("campaign_id", campaign.ID).
+			WithError(err).Error("Failed to store campaign failed log.")
+		return
+	}
+}
+
+// logFailedCampaign updates campaign status to failed & inserts campaign  failed log.
+func logFailedCampaign(ctx context.Context, store storage.Storage, campaign *entities.Campaign, description string) error {
```
Comment (gudgl) [inline consumers/campaigner/main.go:281]: Maybe we should rename this to some name that is saying that its updating the campaign status

File: consumers/campaigner/main.go [hunk 14]
```diff
@@ -90,18 +90,18 @@ func (h *MessageHandler) HandleMessage(m *nsq.Message) (err error) {
 	if err != nil {
 		logEntry.WithError(err).Error("unable to prepare campaign template data")
 
-		err = setStatusFailed(ctx, h.s, campaign)
+		err = logFailedCampaign(ctx, h.s, campaign, "failed to prepare campaign: parseTemplate")
```
Comment (gudgl) [inline consumers/campaigner/main.go:93]: i think its more descriptive if you just set the description to `failed to parse template`

File: consumers/campaigner/main.go [hunk 15]
```diff
@@ -90,18 +90,18 @@ func (h *MessageHandler) HandleMessage(m *nsq.Message) (err error) {
...
 
 		return nil
 	}
 
-	err = processSubscribers(ctx, msg, campaign, parsedTemplate, h.s, svc, logEntry)
+	err = processSubscribers(ctx, m, msg, campaign, parsedTemplate, h.s, svc, logEntry)
 	if err != nil {
 		// TODO return wrapped errors and do the logging here instead of inside processSubscribers
-		err = setStatusFailed(ctx, h.s, campaign)
+		err = logFailedCampaign(ctx, h.s, campaign, "failed to prepare campaign: processSubscribers")
```
Comment (gudgl) [inline consumers/campaigner/main.go:104]: here also `failed to process subscribers`

File: consumers/campaigner/main.go (hunk 13 above)
Comment (Dzalevski) [reply consumers/campaigner/main.go:281]: Hmm i have comment what's doing i don't know any better name? @gudgl

File: storage/campaignfailedlog.go [hunk 16]
```diff
@@ -0,0 +1,46 @@
...
+import (
+	"fmt"
+
+	"github.com/segmentio/ksuid"
+
+	"github.com/mailbadger/app/entities"
+)
+
+// CreateReport creates a report.
+func (db *store) CreateCampaignFailedLog(l *entities.CampaignFailedLog) error {
```
Comment (FilipNikolovski) [inline storage/campaignfailedlog.go:12]: Do we actually need this method? It's a bit confusing to have CreateCampaignFailedLog and LogFailedCampaign methods since we'll most likely only be using one of them.

Comment (Dzalevski) [reply storage/campaignfailedlog.go:12]: @FilipNikolovski Yes you are right.

File: consumers/campaigner/main.go (hunk 13 above)
Comment (gudgl) [reply consumers/campaigner/main.go:281]: I just think that the main goal here is to update the campaign status to failed

**Review by FilipNikolovski — APPROVED** [review]
